import { EventCardProps } from '@/types';

export const eventsList: EventCardProps[] = [
  {
    typeOfEvent: 'workshop',
    title: 'code-camp-5-title',
    buttonText: 'code-camp-5',
    buttonLink: '/events/workshops/code-camp-5',
    cardImage: '/images/workshops/2024/code-camp-5-preview.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'workshop',
    title: 'code-camp-4-title',
    buttonText: 'code-camp-4',
    buttonLink: '/events/workshops/code-camp-4',
    cardImage: '/images/workshops/2024/code-camp-4-preview.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'workshop',
    title: 'code-camp-3-title',
    buttonText: 'code-camp-3',
    buttonLink: '/events/workshops/code-camp-3',
    cardImage: '/images/workshops/2023/code-camp-3-preview.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'hackathon',
    title: 'hackathon2023-title',
    buttonText: 'hackathon2023',
    buttonLink: '/events/hackathons/hackathon2023',
    cardImage: '/images/hackathon2023/hackathon2023.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'workshop',
    title: 'code-camp-2-title',
    buttonText: 'code-camp-2',
    buttonLink: '/events/workshops/code-camp-2',
    cardImage: '/images/workshops/2023/code-camp-2-preview.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'workshop',
    title: 'code-camp-1-title',
    buttonText: 'code-camp-1',
    buttonLink: '/events/workshops/code-camp-1',
    cardImage: '/images/workshops/2023/code-camp-1-preview.webp',
    lastModified: '2024-03-11',
    show: true,
  },
  {
    typeOfEvent: 'hackathon',
    title: 'hackathon2022-title',
    buttonText: 'hackathon2022',
    buttonLink: '/events/hackathons/hackathon2022',
    cardImage: '/images/hackathon2022/hackathon2022.webp',
    lastModified: '2024-03-11',
    show: true,
  },
];
